### ISSUE TITLE
Linking errors?

### ISSUE THREAD

**Issue by rebcabin** [blas-lapack-rs/cblas-sys#1]
I have a working program in C that uses cblas and lapacke, so I have these things installed correctly on my system. I am trying to get your sample https://github.com/blas-lapack-rs/cblas to build in rust. I have worked through many of the samples in the rust book, so I know that basic rust is working on my machine. I get link errors when I try cargo build, but I get no compile errors.

Here is a pointer to my working C program. In it, you will see a CMakeLists.txt that points to my installations of cblas and lapacke. https://www.dropbox.com/s/hp9nsae54weclo3/kalman_sample_c.tgz

Here is a pointer to my non-working copy of your rust program. In it, you will see a proper cargo.toml. The crates all download and install correctly, just when I add a reference to cblas_dgemm, rust is not able to find it https://www.dropbox.com/s/um3q82ebqn5pvbd/kalman_sample_rust.tgz.

Here is my cargo compile log (--verbose option applied): https://www.dropbox.com/s/ghk1lk7phul7ilt/cargo_build_log.txt

I would be very grateful for assistance, as I am currently blocked by this problem!

**Comment by rebcabin** [comment]
I noticed that the file, libcblas-99fa0bd9c58fca09.rmeta, contains the string "dgemm," but not the string "cblas_dgemm." Apparently, the rust compiler is looking for "cblas_dgemm," but the library is only providing "dgemm?"

**Comment by IvanUkhov** [comment]
Hi, try linking to OpenBLAS by adding the following line:

```rust
extern crate openblas_src;
```

Also, I see that you try to use both C and Fortran. One should be enough.

**Comment by rebcabin** [comment]
Fabulous. That did it. Thanks a lot. (yes, i was vacilating between C and Fortran, but left in both references in CMakeLists so I didn't have to go hunting for them again).
